DROP table users if exists;
DROP table user_roles if exists;
CREATE TABLE users (name VARCHAR(50),pass VARCHAR(50));
CREATE TABLE user_roles (user_name VARCHAR(50), role_name VARCHAR(50));
INSERT INTO users(name, pass) VALUES ('admin', 'admin');
INSERT INTO users(name, pass) VALUES ('user', 'user');
INSERT INTO user_roles(user_name, role_name) VALUES ('admin', 'ADMIN');
INSERT INTO user_roles(user_name, role_name) VALUES ('user', 'USER');
insert into Person(name, email) values ('admin', 'admin@admin.com'); 
insert into Person(name, email) values ('user', 'user@user.com'); 
insert into Account(name, currency, amount, person_id) values ('user_USD', 'DOLLAR', 100, 2); 
insert into Account(name, currency, amount, person_id) values ('user_EUR', 'EURO', 200, 2); 
