package com.epam.cdp.bankmodel.exception;


/**
 * The Class InvalidInputParametersException.
 * @author Roman_Konovalov
 *
 */
public class InvalidInputParametersException extends RuntimeException {

	/** Autogenerated uid. */
	private static final long serialVersionUID = -8355327513537124628L;

	/**
	 * Creates new instance of {@link InvalidInputParametersException}.
	 */
	public InvalidInputParametersException() {
		super();
	}

	/**
	 * Creates new instance of {@link InvalidInputParametersException}.
	 *
	 * @param message the message
	 * @param cause the cause
	 */
	public InvalidInputParametersException(final String message, final Throwable cause) {
		super(message, cause);
	}

	/**
	 * Creates new instance of {@link InvalidInputParametersException}.
	 *
	 * @param message the message
	 */
	public InvalidInputParametersException(final String message) {
		super(message);
	}

	/**
	 * Creates new instance of {@link InvalidInputParametersException}.
	 *
	 * @param cause the cause
	 */
	public InvalidInputParametersException(final Throwable cause) {
		super(cause);
	}
}